### PR TITLE
added index

### PR DESCRIPTION
**Pull request by ellisthomas**

### CODE REVIEW

**Comment by zoeames** [comment]
@ellisthomas is this ready for me to look at?

**Comment by ellisthomas** [comment]
DONE!

**Comment by zoeames** [comment]
@ellisthomas you are very close.  functionally it works.  however your main.js file is not actually augmenting the iife.  Instead of:
```function listInventory (cars) {```
you should have something like:
```oldcarlot.listInventory (cars) {```

**Comment by ellisthomas** [comment]
Changes made to PR

**Comment by zoeames** [comment]
looks good!!!
👍

**Pull request merged**
